// SPDX-License-Identifier: MPL-2.0

//! Catppuccin palette data and its shared mapping to Runyte theme roles.

use super::{
    JUMP_LABEL_DARK_PRIMARY, JUMP_LABEL_DARK_SECONDARY, JUMP_LABEL_LIGHT_PRIMARY,
    JUMP_LABEL_LIGHT_SECONDARY, ThemeDefinition, syntax_theme,
};

/// Catppuccin's shared palette roles, adapted to Runyte's presentation roles.
///
/// The four flavours intentionally share this mapping so a syntax or editor
/// role does not change meaning when someone moves between them. Selection and
/// diff backgrounds are palette-local tints because Runyte fills whole cells
/// for those roles, while Catppuccin's accent colours are designed as text.
struct CatppuccinPalette {
    base: &'static str,
    mantle: &'static str,
    text: &'static str,
    overlay0: &'static str,
    overlay2: &'static str,
    blue: &'static str,
    sapphire: &'static str,
    sky: &'static str,
    teal: &'static str,
    green: &'static str,
    yellow: &'static str,
    peach: &'static str,
    red: &'static str,
    mauve: &'static str,
    lavender: &'static str,
    jump_label_primary: &'static str,
    jump_label_secondary: &'static str,
    cursor_select: &'static str,
    selection: &'static str,
    selection_primary: &'static str,
    diff_added: &'static str,
    diff_removed: &'static str,
    diff_changed: &'static str,
}

fn catppuccin_theme(palette: CatppuccinPalette) -> ThemeDefinition {
    ThemeDefinition {
        background: palette.base.into(),
        foreground: palette.text.into(),
        muted: palette.overlay0.into(),
        whitespace: None,
        jump_text_muted: None,
        accent: palette.blue.into(),
        cursor_normal: Some(palette.blue.into()),
        cursor_insert: Some(palette.red.into()),
        cursor_replace: None,
        cursor_select: Some(palette.cursor_select.into()),
        cursor_command: Some(palette.mauve.into()),
        directory: Some(palette.blue.into()),
        selection: palette.selection.into(),
        selection_primary: Some(palette.selection_primary.into()),
        fuzzy_match_secondary: None,
        fuzzy_match_primary: None,
        status_background: palette.mantle.into(),
        status_foreground: palette.text.into(),
        error: palette.red.into(),
        warning: Some(palette.peach.into()),
        info: Some(palette.green.into()),
        jump_label_immediate: Some(palette.red.into()),
        jump_label_primary: palette.jump_label_primary.into(),
        jump_label_secondary: palette.jump_label_secondary.into(),
        change_added: Some(palette.green.into()),
        change_modified: Some(palette.yellow.into()),
        change_removed: Some(palette.red.into()),
        diff_added: Some(palette.diff_added.into()),
        diff_removed: Some(palette.diff_removed.into()),
        diff_changed: Some(palette.diff_changed.into()),
        syntax: syntax_theme(&[
            ("attribute", palette.yellow),
            ("comment", palette.overlay0),
            ("constant", palette.peach),
            ("constructor", palette.sapphire),
            ("function", palette.blue),
            ("keyword", palette.mauve),
            ("label", palette.sapphire),
            ("namespace", palette.teal),
            ("number", palette.peach),
            ("operator", palette.sky),
            ("property", palette.lavender),
            ("punctuation", palette.overlay2),
            ("string", palette.green),
            ("tag", palette.mauve),
            ("type", palette.yellow),
            ("variable", palette.text),
        ]),
    }
}

pub(super) fn themes() -> impl Iterator<Item = (String, ThemeDefinition)> {
    [
        (
            "latte",
            CatppuccinPalette {
                base: "#eff1f5",
                mantle: "#e6e9ef",
                text: "#4c4f69",
                overlay0: "#9ca0b0",
                overlay2: "#7c7f93",
                blue: "#1e66f5",
                sapphire: "#209fb5",
                sky: "#04a5e5",
                teal: "#179299",
                green: "#40a02b",
                yellow: "#df8e1d",
                peach: "#fe640b",
                red: "#d20f39",
                mauve: "#8839ef",
                lavender: "#7287fd",
                jump_label_primary: JUMP_LABEL_LIGHT_PRIMARY,
                jump_label_secondary: JUMP_LABEL_LIGHT_SECONDARY,
                cursor_select: "#c45500",
                selection: "#c3d4f3",
                selection_primary: "#f6d3bd",
                diff_added: "#e3eed8",
                diff_removed: "#f4d9df",
                diff_changed: "#f5e3cf",
            },
        ),
        (
            "frappe",
            CatppuccinPalette {
                base: "#303446",
                mantle: "#292c3c",
                text: "#c6d0f5",
                overlay0: "#737994",
                overlay2: "#949cbb",
                blue: "#8caaee",
                sapphire: "#85c1dc",
                sky: "#99d1db",
                teal: "#81c8be",
                green: "#a6d189",
                yellow: "#e5c890",
                peach: "#ef9f76",
                red: "#e78284",
                mauve: "#ca9ee6",
                lavender: "#babbf1",
                jump_label_primary: JUMP_LABEL_DARK_PRIMARY,
                jump_label_secondary: JUMP_LABEL_DARK_SECONDARY,
                cursor_select: "#ef9f76",
                selection: "#414c66",
                selection_primary: "#59473e",
                diff_added: "#35463d",
                diff_removed: "#4b373d",
                diff_changed: "#4a4038",
            },
        ),
        (
            "macchiato",
            CatppuccinPalette {
                base: "#24273a",
                mantle: "#1e2030",
                text: "#cad3f5",
                overlay0: "#6e738d",
                overlay2: "#939ab7",
                blue: "#8aadf4",
                sapphire: "#7dc4e4",
                sky: "#91d7e3",
                teal: "#8bd5ca",
                green: "#a6da95",
                yellow: "#eed49f",
                peach: "#f5a97f",
                red: "#ed8796",
                mauve: "#c6a0f6",
                lavender: "#b7bdf8",
                jump_label_primary: JUMP_LABEL_DARK_PRIMARY,
                jump_label_secondary: JUMP_LABEL_DARK_SECONDARY,
                cursor_select: "#f5a97f",
                selection: "#35405b",
                selection_primary: "#504036",
                diff_added: "#293d35",
                diff_removed: "#402e36",
                diff_changed: "#40372f",
            },
        ),
        (
            "mocha",
            CatppuccinPalette {
                base: "#1e1e2e",
                mantle: "#181825",
                text: "#cdd6f4",
                overlay0: "#6c7086",
                overlay2: "#9399b2",
                blue: "#89b4fa",
                sapphire: "#74c7ec",
                sky: "#89dceb",
                teal: "#94e2d5",
                green: "#a6e3a1",
                yellow: "#f9e2af",
                peach: "#fab387",
                red: "#f38ba8",
                mauve: "#cba6f7",
                lavender: "#b4befe",
                jump_label_primary: JUMP_LABEL_DARK_PRIMARY,
                jump_label_secondary: JUMP_LABEL_DARK_SECONDARY,
                cursor_select: "#fab387",
                selection: "#2e3d59",
                selection_primary: "#49392f",
                diff_added: "#23362d",
                diff_removed: "#38272f",
                diff_changed: "#382f28",
            },
        ),
    ]
    .into_iter()
    .map(|(name, palette)| (name.to_owned(), catppuccin_theme(palette)))
}
