// SPDX-License-Identifier: MPL-2.0

//! Runyte's original standalone theme definitions.

use std::collections::HashMap;

use super::{
    JUMP_LABEL_DARK_PRIMARY, JUMP_LABEL_DARK_SECONDARY, JUMP_LABEL_LIGHT_PRIMARY,
    JUMP_LABEL_LIGHT_SECONDARY, ThemeDefinition, syntax_theme,
};

pub(super) fn themes() -> impl Iterator<Item = (String, ThemeDefinition)> {
    let mut themes = HashMap::new();
    let mut base16 = ThemeDefinition {
        // Base16's comment grey is dark enough that dimmed text on either
        // selection ground was all but invisible — 1.08:1 on the blue one.
        // The grounds themselves stand off the background well, so only
        // the dimmed text moves.
        jump_text_muted: Some("#a3a3a3".into()),
        cursor_insert: Some("#ab4642".into()),
        cursor_select: Some("#dc9656".into()),
        cursor_command: Some("#ba8baf".into()),
        directory: Some("#7cafc2".into()),
        selection: "#365864".into(),
        selection_primary: Some("#5a3b2a".into()),
        jump_label_immediate: Some("#e65c57".into()),
        ..ThemeDefinition::default()
    };
    base16
        .syntax
        .insert("property".into(), base16.foreground.clone());
    themes.insert("base16".into(), base16);
    // `dark` and `light` are the two themes people reach for by name, so
    // they are neutral by design: no palette identity of their own, just a
    // legible pair that reads correctly on a dark and on a light terminal.
    themes.insert(
        "dark".into(),
        ThemeDefinition {
            background: "#16181d".into(),
            foreground: "#d6dae0".into(),
            muted: "#6b7280".into(),
            whitespace: None,
            jump_text_muted: None,
            accent: "#6cb6ff".into(),
            cursor_normal: None,
            cursor_insert: Some("#f87171".into()),
            cursor_select: Some("#f0a868".into()),
            cursor_command: Some("#d2a8ff".into()),
            directory: Some("#6cb6ff".into()),
            selection: "#34506a".into(),
            selection_primary: Some("#5a3f2b".into()),
            fuzzy_match_secondary: None,
            fuzzy_match_primary: None,
            status_background: "#21242b".into(),
            status_foreground: "#d6dae0".into(),
            error: "#f87171".into(),
            warning: Some("#f0a868".into()),
            info: Some("#8ddb8c".into()),
            jump_label_immediate: Some("#f87171".into()),
            jump_label_primary: JUMP_LABEL_DARK_PRIMARY.into(),
            jump_label_secondary: JUMP_LABEL_DARK_SECONDARY.into(),
            change_added: Some("#8ddb8c".into()),
            change_modified: Some("#f0a868".into()),
            change_removed: Some("#f87171".into()),
            diff_added: Some("#16281c".into()),
            diff_removed: Some("#2b1a1e".into()),
            diff_changed: Some("#2a2318".into()),
            syntax: syntax_theme(&[
                ("attribute", "#d2a8ff"),
                ("comment", "#6b7280"),
                ("constant", "#f0a868"),
                ("constructor", "#6cb6ff"),
                ("function", "#6cb6ff"),
                ("keyword", "#d2a8ff"),
                ("label", "#f0a868"),
                ("namespace", "#7ee0c0"),
                ("number", "#f0a868"),
                ("operator", "#d6dae0"),
                ("property", "#d6dae0"),
                ("punctuation", "#9aa3af"),
                ("string", "#8ddb8c"),
                ("tag", "#f87171"),
                ("type", "#7ee0c0"),
                ("variable", "#d6dae0"),
            ]),
        },
    );
    themes.insert(
        "light".into(),
        ThemeDefinition {
            background: "#fbfbfa".into(),
            foreground: "#24292f".into(),
            muted: "#6e7781".into(),
            whitespace: None,
            jump_text_muted: Some("#a8adb2".into()),
            accent: "#0550ae".into(),
            cursor_normal: Some("#0550ae".into()),
            cursor_insert: Some("#cf222e".into()),
            cursor_select: Some("#953800".into()),
            cursor_command: Some("#8250df".into()),
            directory: Some("#0550ae".into()),
            selection: "#cfe3ff".into(),
            selection_primary: Some("#ffe2c2".into()),
            fuzzy_match_secondary: None,
            fuzzy_match_primary: None,
            status_background: "#e8eaed".into(),
            status_foreground: "#24292f".into(),
            error: "#b3261e".into(),
            warning: Some("#953800".into()),
            info: Some("#0a6b26".into()),
            jump_label_immediate: Some("#b3261e".into()),
            jump_label_primary: JUMP_LABEL_LIGHT_PRIMARY.into(),
            jump_label_secondary: JUMP_LABEL_LIGHT_SECONDARY.into(),
            change_added: Some("#0a6b26".into()),
            change_modified: Some("#953800".into()),
            change_removed: Some("#b3261e".into()),
            diff_added: Some("#e3f5e6".into()),
            diff_removed: Some("#fce4e4".into()),
            diff_changed: Some("#fdf0dc".into()),
            syntax: syntax_theme(&[
                ("attribute", "#8250df"),
                ("comment", "#6e7781"),
                ("constant", "#953800"),
                ("constructor", "#0550ae"),
                ("function", "#0550ae"),
                ("keyword", "#8250df"),
                ("label", "#953800"),
                ("namespace", "#0f6b5c"),
                ("number", "#953800"),
                ("operator", "#24292f"),
                ("property", "#24292f"),
                ("punctuation", "#57606a"),
                ("string", "#0a6b26"),
                ("tag", "#b3261e"),
                ("type", "#0f6b5c"),
                ("variable", "#24292f"),
            ]),
        },
    );
    themes.insert(
        "paper".into(),
        ThemeDefinition {
            background: "#eeeeee".into(),
            foreground: "#303030".into(),
            muted: "#808080".into(),
            whitespace: None,
            jump_text_muted: Some("#aaaaaa".into()),
            accent: "#005faf".into(),
            cursor_normal: Some("#005faf".into()),
            cursor_insert: Some("#af0000".into()),
            cursor_select: Some("#d75f00".into()),
            cursor_command: Some("#8700af".into()),
            directory: Some("#005faf".into()),
            selection: "#afd7ff".into(),
            selection_primary: Some("#ffd7af".into()),
            fuzzy_match_secondary: None,
            fuzzy_match_primary: None,
            status_background: "#d0d0d0".into(),
            status_foreground: "#202020".into(),
            error: "#af0000".into(),
            warning: Some("#d75f00".into()),
            info: Some("#005f00".into()),
            jump_label_immediate: Some("#af0000".into()),
            jump_label_primary: JUMP_LABEL_LIGHT_PRIMARY.into(),
            jump_label_secondary: JUMP_LABEL_LIGHT_SECONDARY.into(),
            change_added: Some("#005f00".into()),
            change_modified: Some("#d75f00".into()),
            change_removed: Some("#af0000".into()),
            diff_added: Some("#dcecdc".into()),
            diff_removed: Some("#f2dcdc".into()),
            diff_changed: Some("#f0e6d2".into()),
            syntax: syntax_theme(&[
                ("attribute", "#8700af"),
                ("comment", "#808080"),
                ("constant", "#d75f00"),
                ("constructor", "#005faf"),
                ("function", "#005faf"),
                ("keyword", "#8700af"),
                ("label", "#d75f00"),
                ("namespace", "#875f00"),
                ("number", "#d75f00"),
                ("operator", "#303030"),
                ("property", "#303030"),
                ("punctuation", "#606060"),
                ("string", "#005f00"),
                ("tag", "#af0000"),
                ("type", "#875f00"),
                ("variable", "#303030"),
            ]),
        },
    );
    themes.insert(
        "gruvbox".into(),
        ThemeDefinition {
            background: "#282828".into(),
            foreground: "#ebdbb2".into(),
            muted: "#928374".into(),
            whitespace: None,
            jump_text_muted: None,
            accent: "#fabd2f".into(),
            cursor_normal: None,
            cursor_insert: Some("#fb4934".into()),
            cursor_select: Some("#fe8019".into()),
            cursor_command: Some("#d3869b".into()),
            directory: Some("#83a598".into()),
            selection: "#3c5154".into(),
            selection_primary: Some("#66502f".into()),
            fuzzy_match_secondary: None,
            fuzzy_match_primary: None,
            status_background: "#3c3836".into(),
            status_foreground: "#ebdbb2".into(),
            error: "#fb4934".into(),
            warning: Some("#fe8019".into()),
            info: Some("#b8bb26".into()),
            jump_label_immediate: Some("#ff7b6b".into()),
            jump_label_primary: JUMP_LABEL_DARK_PRIMARY.into(),
            jump_label_secondary: JUMP_LABEL_DARK_SECONDARY.into(),
            change_added: Some("#b8bb26".into()),
            change_modified: Some("#fabd2f".into()),
            change_removed: Some("#fb4934".into()),
            diff_added: Some("#26301f".into()),
            diff_removed: Some("#3a2424".into()),
            diff_changed: Some("#38301c".into()),
            syntax: syntax_theme(&[
                ("attribute", "#fabd2f"),
                ("comment", "#928374"),
                ("constant", "#d3869b"),
                ("constructor", "#8ec07c"),
                ("function", "#b8bb26"),
                ("keyword", "#fb4934"),
                ("label", "#fe8019"),
                ("namespace", "#fabd2f"),
                ("number", "#d3869b"),
                ("operator", "#ebdbb2"),
                ("property", "#ebdbb2"),
                ("punctuation", "#a89984"),
                ("string", "#b8bb26"),
                ("tag", "#fb4934"),
                ("type", "#fabd2f"),
                ("variable", "#ebdbb2"),
            ]),
        },
    );
    themes.into_iter()
}
